// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC56AH-salv93XsZLsDZ4P5Y6zAQBRLPRw',
    appId: '1:332049197085:web:1b88088bd8f4413c6ffef4',
    messagingSenderId: '332049197085',
    projectId: 'mediation-elprofessor',
    authDomain: 'mediation-elprofessor.firebaseapp.com',
    storageBucket: 'mediation-elprofessor.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOiRrCo2PcREHoiWubYTiNDXfemLShntg',
    appId: '1:332049197085:android:80f3a2cd574ffe906ffef4',
    messagingSenderId: '332049197085',
    projectId: 'mediation-elprofessor',
    storageBucket: 'mediation-elprofessor.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXSSazO9F5KQtiJ0otELhQGew9SDofrFs',
    appId: '1:332049197085:ios:556f00e38e0f47f76ffef4',
    messagingSenderId: '332049197085',
    projectId: 'mediation-elprofessor',
    storageBucket: 'mediation-elprofessor.firebasestorage.app',
    androidClientId: '332049197085-bepvs67g0d6vbu2bsfgcqn5vq2bv5205.apps.googleusercontent.com',
    iosClientId: '332049197085-f2ttm3cgnm8gk4oa7gfhl98m5lod10o6.apps.googleusercontent.com',
    iosBundleId: 'com.elprofvirus.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXSSazO9F5KQtiJ0otELhQGew9SDofrFs',
    appId: '1:332049197085:ios:556f00e38e0f47f76ffef4',
    messagingSenderId: '332049197085',
    projectId: 'mediation-elprofessor',
    storageBucket: 'mediation-elprofessor.firebasestorage.app',
    androidClientId: '332049197085-bepvs67g0d6vbu2bsfgcqn5vq2bv5205.apps.googleusercontent.com',
    iosClientId: '332049197085-f2ttm3cgnm8gk4oa7gfhl98m5lod10o6.apps.googleusercontent.com',
    iosBundleId: 'com.elprofvirus.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC56AH-salv93XsZLsDZ4P5Y6zAQBRLPRw',
    appId: '1:332049197085:web:c8651496b007decf6ffef4',
    messagingSenderId: '332049197085',
    projectId: 'mediation-elprofessor',
    authDomain: 'mediation-elprofessor.firebaseapp.com',
    storageBucket: 'mediation-elprofessor.firebasestorage.app',
  );
}
